import './App.css';
import './style.css';
import Navbar from './navbar/Navbar';

/*  TODO
- Navbar
- Landing Page (Profile)
- Experiences/Education/Skills
- Projects
*/

function App() {
  return (
    <div class='main-div'>

      <Navbar></Navbar>

      <main>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non sapien et nisi viverra consequat vitae vitae neque. Donec sit amet sapien sit amet ipsum ultrices tincidunt vitae non ipsum. In finibus, ligula eu volutpat vehicula, dui tortor sodales magna, sit amet cursus ipsum erat eget ante. Aliquam viverra volutpat velit. Nullam luctus lectus nibh, sit amet auctor magna accumsan quis. Morbi imperdiet sit amet risus vel vehicula. In et tristique felis. Aenean quis urna ex. Maecenas vel lectus sem. Integer auctor, neque ac convallis cursus, velit arcu faucibus odio, in tempus magna sem ut tortor. Donec id augue eget elit condimentum ultricies in id orci. Nulla id sodales enim, at posuere purus. Suspendisse condimentum maximus ligula eu euismod.
          Aenean ac magna sed justo porta pellentesque. Curabitur egestas diam eu aliquet maximus. Nunc vitae velit ac purus ultricies molestie in sed massa. Proin nec felis elit. Mauris felis felis, mollis cursus ullamcorper sit amet, pharetra at ex. Cras consectetur feugiat risus in fermentum. Ut dapibus purus sit amet enim auctor, eget blandit lacus viverra. Nulla vitae blandit neque. Aliquam lobortis dictum leo nec tempor. Etiam dignissim in libero id commodo. Proin tristique tellus nec urna iaculis, vel pharetra ipsum mattis.
          Suspendisse metus eros, interdum eget diam sit amet, placerat elementum ante. Aliquam sapien odio, tristique eu eleifend sit amet, congue sed metus. Quisque justo nibh, viverra ut porttitor in, vestibulum a lorem. Quisque velit turpis, mollis ac auctor eu, tempus eget odio. Sed ac blandit risus. Aenean facilisis eleifend velit, non lobortis ligula lobortis non. Fusce nec nulla pharetra, efficitur est non, pretium est. Suspendisse cursus mi vitae commodo venenatis. Mauris lobortis aliquet dolor, sed malesuada felis dictum nec. Duis facilisis nisl non dapibus vehicula.
          Nulla non risus ac lectus tempus lobortis ac non sem. Duis ut malesuada enim. Etiam vitae eleifend arcu. Sed vitae tellus risus. Duis turpis erat, scelerisque in magna sit amet, tincidunt vulputate diam. Fusce justo ex, sodales id tortor et, sollicitudin aliquet massa. Nullam elit tellus, mattis ac consectetur sit amet, venenatis eget neque. Aenean eu dui a ipsum vulputate egestas. Mauris varius ut tellus eget mollis. Integer sed ipsum id elit elementum iaculis. Nulla facilisi. Curabitur id purus nisi. Vestibulum efficitur sapien eget interdum dapibus. Phasellus aliquam nunc ut sapien laoreet, sit amet imperdiet tellus placerat. Nulla eu pellentesque arcu. Maecenas congue ultricies risus, ut volutpat dui ornare sit amet.
          Nulla rhoncus tempor lectus, in faucibus quam auctor ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur facilisis sed quam eu gravida. Morbi purus ipsum, viverra sed finibus varius, semper finibus arcu. Fusce porttitor tellus ligula, nec consectetur lectus egestas id. Phasellus nec varius est. Sed in orci dapibus, dictum lectus eu, faucibus odio. Vivamus volutpat volutpat erat, ac euismod turpis accumsan ut.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non sapien et nisi viverra consequat vitae vitae neque. Donec sit amet sapien sit amet ipsum ultrices tincidunt vitae non ipsum. In finibus, ligula eu volutpat vehicula, dui tortor sodales magna, sit amet cursus ipsum erat eget ante. Aliquam viverra volutpat velit. Nullam luctus lectus nibh, sit amet auctor magna accumsan quis. Morbi imperdiet sit amet risus vel vehicula. In et tristique felis. Aenean quis urna ex. Maecenas vel lectus sem. Integer auctor, neque ac convallis cursus, velit arcu faucibus odio, in tempus magna sem ut tortor. Donec id augue eget elit condimentum ultricies in id orci. Nulla id sodales enim, at posuere purus. Suspendisse condimentum maximus ligula eu euismod.
          Aenean ac magna sed justo porta pellentesque. Curabitur egestas diam eu aliquet maximus. Nunc vitae velit ac purus ultricies molestie in sed massa. Proin nec felis elit. Mauris felis felis, mollis cursus ullamcorper sit amet, pharetra at ex. Cras consectetur feugiat risus in fermentum. Ut dapibus purus sit amet enim auctor, eget blandit lacus viverra. Nulla vitae blandit neque. Aliquam lobortis dictum leo nec tempor. Etiam dignissim in libero id commodo. Proin tristique tellus nec urna iaculis, vel pharetra ipsum mattis.
          Suspendisse metus eros, interdum eget diam sit amet, placerat elementum ante. Aliquam sapien odio, tristique eu eleifend sit amet, congue sed metus. Quisque justo nibh, viverra ut porttitor in, vestibulum a lorem. Quisque velit turpis, mollis ac auctor eu, tempus eget odio. Sed ac blandit risus. Aenean facilisis eleifend velit, non lobortis ligula lobortis non. Fusce nec nulla pharetra, efficitur est non, pretium est. Suspendisse cursus mi vitae commodo venenatis. Mauris lobortis aliquet dolor, sed malesuada felis dictum nec. Duis facilisis nisl non dapibus vehicula.
          Nulla non risus ac lectus tempus lobortis ac non sem. Duis ut malesuada enim. Etiam vitae eleifend arcu. Sed vitae tellus risus. Duis turpis erat, scelerisque in magna sit amet, tincidunt vulputate diam. Fusce justo ex, sodales id tortor et, sollicitudin aliquet massa. Nullam elit tellus, mattis ac consectetur sit amet, venenatis eget neque. Aenean eu dui a ipsum vulputate egestas. Mauris varius ut tellus eget mollis. Integer sed ipsum id elit elementum iaculis. Nulla facilisi. Curabitur id purus nisi. Vestibulum efficitur sapien eget interdum dapibus. Phasellus aliquam nunc ut sapien laoreet, sit amet imperdiet tellus placerat. Nulla eu pellentesque arcu. Maecenas congue ultricies risus, ut volutpat dui ornare sit amet.
          Nulla rhoncus tempor lectus, in faucibus quam auctor ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur facilisis sed quam eu gravida. Morbi purus ipsum, viverra sed finibus varius, semper finibus arcu. Fusce porttitor tellus ligula, nec consectetur lectus egestas id. Phasellus nec varius est. Sed in orci dapibus, dictum lectus eu, faucibus odio. Vivamus volutpat volutpat erat, ac euismod turpis accumsan ut.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non sapien et nisi viverra consequat vitae vitae neque. Donec sit amet sapien sit amet ipsum ultrices tincidunt vitae non ipsum. In finibus, ligula eu volutpat vehicula, dui tortor sodales magna, sit amet cursus ipsum erat eget ante. Aliquam viverra volutpat velit. Nullam luctus lectus nibh, sit amet auctor magna accumsan quis. Morbi imperdiet sit amet risus vel vehicula. In et tristique felis. Aenean quis urna ex. Maecenas vel lectus sem. Integer auctor, neque ac convallis cursus, velit arcu faucibus odio, in tempus magna sem ut tortor. Donec id augue eget elit condimentum ultricies in id orci. Nulla id sodales enim, at posuere purus. Suspendisse condimentum maximus ligula eu euismod.
          Aenean ac magna sed justo porta pellentesque. Curabitur egestas diam eu aliquet maximus. Nunc vitae velit ac purus ultricies molestie in sed massa. Proin nec felis elit. Mauris felis felis, mollis cursus ullamcorper sit amet, pharetra at ex. Cras consectetur feugiat risus in fermentum. Ut dapibus purus sit amet enim auctor, eget blandit lacus viverra. Nulla vitae blandit neque. Aliquam lobortis dictum leo nec tempor. Etiam dignissim in libero id commodo. Proin tristique tellus nec urna iaculis, vel pharetra ipsum mattis.
          Suspendisse metus eros, interdum eget diam sit amet, placerat elementum ante. Aliquam sapien odio, tristique eu eleifend sit amet, congue sed metus. Quisque justo nibh, viverra ut porttitor in, vestibulum a lorem. Quisque velit turpis, mollis ac auctor eu, tempus eget odio. Sed ac blandit risus. Aenean facilisis eleifend velit, non lobortis ligula lobortis non. Fusce nec nulla pharetra, efficitur est non, pretium est. Suspendisse cursus mi vitae commodo venenatis. Mauris lobortis aliquet dolor, sed malesuada felis dictum nec. Duis facilisis nisl non dapibus vehicula.
          Nulla non risus ac lectus tempus lobortis ac non sem. Duis ut malesuada enim. Etiam vitae eleifend arcu. Sed vitae tellus risus. Duis turpis erat, scelerisque in magna sit amet, tincidunt vulputate diam. Fusce justo ex, sodales id tortor et, sollicitudin aliquet massa. Nullam elit tellus, mattis ac consectetur sit amet, venenatis eget neque. Aenean eu dui a ipsum vulputate egestas. Mauris varius ut tellus eget mollis. Integer sed ipsum id elit elementum iaculis. Nulla facilisi. Curabitur id purus nisi. Vestibulum efficitur sapien eget interdum dapibus. Phasellus aliquam nunc ut sapien laoreet, sit amet imperdiet tellus placerat. Nulla eu pellentesque arcu. Maecenas congue ultricies risus, ut volutpat dui ornare sit amet.
          Nulla rhoncus tempor lectus, in faucibus quam auctor ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur facilisis sed quam eu gravida. Morbi purus ipsum, viverra sed finibus varius, semper finibus arcu. Fusce porttitor tellus ligula, nec consectetur lectus egestas id. Phasellus nec varius est. Sed in orci dapibus, dictum lectus eu, faucibus odio. Vivamus volutpat volutpat erat, ac euismod turpis accumsan ut.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non sapien et nisi viverra consequat vitae vitae neque. Donec sit amet sapien sit amet ipsum ultrices tincidunt vitae non ipsum. In finibus, ligula eu volutpat vehicula, dui tortor sodales magna, sit amet cursus ipsum erat eget ante. Aliquam viverra volutpat velit. Nullam luctus lectus nibh, sit amet auctor magna accumsan quis. Morbi imperdiet sit amet risus vel vehicula. In et tristique felis. Aenean quis urna ex. Maecenas vel lectus sem. Integer auctor, neque ac convallis cursus, velit arcu faucibus odio, in tempus magna sem ut tortor. Donec id augue eget elit condimentum ultricies in id orci. Nulla id sodales enim, at posuere purus. Suspendisse condimentum maximus ligula eu euismod.
          Aenean ac magna sed justo porta pellentesque. Curabitur egestas diam eu aliquet maximus. Nunc vitae velit ac purus ultricies molestie in sed massa. Proin nec felis elit. Mauris felis felis, mollis cursus ullamcorper sit amet, pharetra at ex. Cras consectetur feugiat risus in fermentum. Ut dapibus purus sit amet enim auctor, eget blandit lacus viverra. Nulla vitae blandit neque. Aliquam lobortis dictum leo nec tempor. Etiam dignissim in libero id commodo. Proin tristique tellus nec urna iaculis, vel pharetra ipsum mattis.
          Suspendisse metus eros, interdum eget diam sit amet, placerat elementum ante. Aliquam sapien odio, tristique eu eleifend sit amet, congue sed metus. Quisque justo nibh, viverra ut porttitor in, vestibulum a lorem. Quisque velit turpis, mollis ac auctor eu, tempus eget odio. Sed ac blandit risus. Aenean facilisis eleifend velit, non lobortis ligula lobortis non. Fusce nec nulla pharetra, efficitur est non, pretium est. Suspendisse cursus mi vitae commodo venenatis. Mauris lobortis aliquet dolor, sed malesuada felis dictum nec. Duis facilisis nisl non dapibus vehicula.
          Nulla non risus ac lectus tempus lobortis ac non sem. Duis ut malesuada enim. Etiam vitae eleifend arcu. Sed vitae tellus risus. Duis turpis erat, scelerisque in magna sit amet, tincidunt vulputate diam. Fusce justo ex, sodales id tortor et, sollicitudin aliquet massa. Nullam elit tellus, mattis ac consectetur sit amet, venenatis eget neque. Aenean eu dui a ipsum vulputate egestas. Mauris varius ut tellus eget mollis. Integer sed ipsum id elit elementum iaculis. Nulla facilisi. Curabitur id purus nisi. Vestibulum efficitur sapien eget interdum dapibus. Phasellus aliquam nunc ut sapien laoreet, sit amet imperdiet tellus placerat. Nulla eu pellentesque arcu. Maecenas congue ultricies risus, ut volutpat dui ornare sit amet.
          Nulla rhoncus tempor lectus, in faucibus quam auctor ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur facilisis sed quam eu gravida. Morbi purus ipsum, viverra sed finibus varius, semper finibus arcu. Fusce porttitor tellus ligula, nec consectetur lectus egestas id. Phasellus nec varius est. Sed in orci dapibus, dictum lectus eu, faucibus odio. Vivamus volutpat volutpat erat, ac euismod turpis accumsan ut.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non sapien et nisi viverra consequat vitae vitae neque. Donec sit amet sapien sit amet ipsum ultrices tincidunt vitae non ipsum. In finibus, ligula eu volutpat vehicula, dui tortor sodales magna, sit amet cursus ipsum erat eget ante. Aliquam viverra volutpat velit. Nullam luctus lectus nibh, sit amet auctor magna accumsan quis. Morbi imperdiet sit amet risus vel vehicula. In et tristique felis. Aenean quis urna ex. Maecenas vel lectus sem. Integer auctor, neque ac convallis cursus, velit arcu faucibus odio, in tempus magna sem ut tortor. Donec id augue eget elit condimentum ultricies in id orci. Nulla id sodales enim, at posuere purus. Suspendisse condimentum maximus ligula eu euismod.
          Aenean ac magna sed justo porta pellentesque. Curabitur egestas diam eu aliquet maximus. Nunc vitae velit ac purus ultricies molestie in sed massa. Proin nec felis elit. Mauris felis felis, mollis cursus ullamcorper sit amet, pharetra at ex. Cras consectetur feugiat risus in fermentum. Ut dapibus purus sit amet enim auctor, eget blandit lacus viverra. Nulla vitae blandit neque. Aliquam lobortis dictum leo nec tempor. Etiam dignissim in libero id commodo. Proin tristique tellus nec urna iaculis, vel pharetra ipsum mattis.
          Suspendisse metus eros, interdum eget diam sit amet, placerat elementum ante. Aliquam sapien odio, tristique eu eleifend sit amet, congue sed metus. Quisque justo nibh, viverra ut porttitor in, vestibulum a lorem. Quisque velit turpis, mollis ac auctor eu, tempus eget odio. Sed ac blandit risus. Aenean facilisis eleifend velit, non lobortis ligula lobortis non. Fusce nec nulla pharetra, efficitur est non, pretium est. Suspendisse cursus mi vitae commodo venenatis. Mauris lobortis aliquet dolor, sed malesuada felis dictum nec. Duis facilisis nisl non dapibus vehicula.
          Nulla non risus ac lectus tempus lobortis ac non sem. Duis ut malesuada enim. Etiam vitae eleifend arcu. Sed vitae tellus risus. Duis turpis erat, scelerisque in magna sit amet, tincidunt vulputate diam. Fusce justo ex, sodales id tortor et, sollicitudin aliquet massa. Nullam elit tellus, mattis ac consectetur sit amet, venenatis eget neque. Aenean eu dui a ipsum vulputate egestas. Mauris varius ut tellus eget mollis. Integer sed ipsum id elit elementum iaculis. Nulla facilisi. Curabitur id purus nisi. Vestibulum efficitur sapien eget interdum dapibus. Phasellus aliquam nunc ut sapien laoreet, sit amet imperdiet tellus placerat. Nulla eu pellentesque arcu. Maecenas congue ultricies risus, ut volutpat dui ornare sit amet.
          Nulla rhoncus tempor lectus, in faucibus quam auctor ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur facilisis sed quam eu gravida. Morbi purus ipsum, viverra sed finibus varius, semper finibus arcu. Fusce porttitor tellus ligula, nec consectetur lectus egestas id. Phasellus nec varius est. Sed in orci dapibus, dictum lectus eu, faucibus odio. Vivamus volutpat volutpat erat, ac euismod turpis accumsan ut.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non sapien et nisi viverra consequat vitae vitae neque. Donec sit amet sapien sit amet ipsum ultrices tincidunt vitae non ipsum. In finibus, ligula eu volutpat vehicula, dui tortor sodales magna, sit amet cursus ipsum erat eget ante. Aliquam viverra volutpat velit. Nullam luctus lectus nibh, sit amet auctor magna accumsan quis. Morbi imperdiet sit amet risus vel vehicula. In et tristique felis. Aenean quis urna ex. Maecenas vel lectus sem. Integer auctor, neque ac convallis cursus, velit arcu faucibus odio, in tempus magna sem ut tortor. Donec id augue eget elit condimentum ultricies in id orci. Nulla id sodales enim, at posuere purus. Suspendisse condimentum maximus ligula eu euismod.
          Aenean ac magna sed justo porta pellentesque. Curabitur egestas diam eu aliquet maximus. Nunc vitae velit ac purus ultricies molestie in sed massa. Proin nec felis elit. Mauris felis felis, mollis cursus ullamcorper sit amet, pharetra at ex. Cras consectetur feugiat risus in fermentum. Ut dapibus purus sit amet enim auctor, eget blandit lacus viverra. Nulla vitae blandit neque. Aliquam lobortis dictum leo nec tempor. Etiam dignissim in libero id commodo. Proin tristique tellus nec urna iaculis, vel pharetra ipsum mattis.
          Suspendisse metus eros, interdum eget diam sit amet, placerat elementum ante. Aliquam sapien odio, tristique eu eleifend sit amet, congue sed metus. Quisque justo nibh, viverra ut porttitor in, vestibulum a lorem. Quisque velit turpis, mollis ac auctor eu, tempus eget odio. Sed ac blandit risus. Aenean facilisis eleifend velit, non lobortis ligula lobortis non. Fusce nec nulla pharetra, efficitur est non, pretium est. Suspendisse cursus mi vitae commodo venenatis. Mauris lobortis aliquet dolor, sed malesuada felis dictum nec. Duis facilisis nisl non dapibus vehicula.
          Nulla non risus ac lectus tempus lobortis ac non sem. Duis ut malesuada enim. Etiam vitae eleifend arcu. Sed vitae tellus risus. Duis turpis erat, scelerisque in magna sit amet, tincidunt vulputate diam. Fusce justo ex, sodales id tortor et, sollicitudin aliquet massa. Nullam elit tellus, mattis ac consectetur sit amet, venenatis eget neque. Aenean eu dui a ipsum vulputate egestas. Mauris varius ut tellus eget mollis. Integer sed ipsum id elit elementum iaculis. Nulla facilisi. Curabitur id purus nisi. Vestibulum efficitur sapien eget interdum dapibus. Phasellus aliquam nunc ut sapien laoreet, sit amet imperdiet tellus placerat. Nulla eu pellentesque arcu. Maecenas congue ultricies risus, ut volutpat dui ornare sit amet.
          Nulla rhoncus tempor lectus, in faucibus quam auctor ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur facilisis sed quam eu gravida. Morbi purus ipsum, viverra sed finibus varius, semper finibus arcu. Fusce porttitor tellus ligula, nec consectetur lectus egestas id. Phasellus nec varius est. Sed in orci dapibus, dictum lectus eu, faucibus odio. Vivamus volutpat volutpat erat, ac euismod turpis accumsan ut.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non sapien et nisi viverra consequat vitae vitae neque. Donec sit amet sapien sit amet ipsum ultrices tincidunt vitae non ipsum. In finibus, ligula eu volutpat vehicula, dui tortor sodales magna, sit amet cursus ipsum erat eget ante. Aliquam viverra volutpat velit. Nullam luctus lectus nibh, sit amet auctor magna accumsan quis. Morbi imperdiet sit amet risus vel vehicula. In et tristique felis. Aenean quis urna ex. Maecenas vel lectus sem. Integer auctor, neque ac convallis cursus, velit arcu faucibus odio, in tempus magna sem ut tortor. Donec id augue eget elit condimentum ultricies in id orci. Nulla id sodales enim, at posuere purus. Suspendisse condimentum maximus ligula eu euismod.
          Aenean ac magna sed justo porta pellentesque. Curabitur egestas diam eu aliquet maximus. Nunc vitae velit ac purus ultricies molestie in sed massa. Proin nec felis elit. Mauris felis felis, mollis cursus ullamcorper sit amet, pharetra at ex. Cras consectetur feugiat risus in fermentum. Ut dapibus purus sit amet enim auctor, eget blandit lacus viverra. Nulla vitae blandit neque. Aliquam lobortis dictum leo nec tempor. Etiam dignissim in libero id commodo. Proin tristique tellus nec urna iaculis, vel pharetra ipsum mattis.
          Suspendisse metus eros, interdum eget diam sit amet, placerat elementum ante. Aliquam sapien odio, tristique eu eleifend sit amet, congue sed metus. Quisque justo nibh, viverra ut porttitor in, vestibulum a lorem. Quisque velit turpis, mollis ac auctor eu, tempus eget odio. Sed ac blandit risus. Aenean facilisis eleifend velit, non lobortis ligula lobortis non. Fusce nec nulla pharetra, efficitur est non, pretium est. Suspendisse cursus mi vitae commodo venenatis. Mauris lobortis aliquet dolor, sed malesuada felis dictum nec. Duis facilisis nisl non dapibus vehicula.
          Nulla non risus ac lectus tempus lobortis ac non sem. Duis ut malesuada enim. Etiam vitae eleifend arcu. Sed vitae tellus risus. Duis turpis erat, scelerisque in magna sit amet, tincidunt vulputate diam. Fusce justo ex, sodales id tortor et, sollicitudin aliquet massa. Nullam elit tellus, mattis ac consectetur sit amet, venenatis eget neque. Aenean eu dui a ipsum vulputate egestas. Mauris varius ut tellus eget mollis. Integer sed ipsum id elit elementum iaculis. Nulla facilisi. Curabitur id purus nisi. Vestibulum efficitur sapien eget interdum dapibus. Phasellus aliquam nunc ut sapien laoreet, sit amet imperdiet tellus placerat. Nulla eu pellentesque arcu. Maecenas congue ultricies risus, ut volutpat dui ornare sit amet.
          Nulla rhoncus tempor lectus, in faucibus quam auctor ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur facilisis sed quam eu gravida. Morbi purus ipsum, viverra sed finibus varius, semper finibus arcu. Fusce porttitor tellus ligula, nec consectetur lectus egestas id. Phasellus nec varius est. Sed in orci dapibus, dictum lectus eu, faucibus odio. Vivamus volutpat volutpat erat, ac euismod turpis accumsan ut.
        </p>
      </main>
    </div>
  );
}

export default App;
